### ISSUE TITLE
Function name changed in recent UFL update

### ISSUE THREAD

**Issue by SamAhnert** [dynamicslab/hydrogym#102]
According to:
https://github.com/FEniCS/ufl/commit/8f44275dcf88f8c853487fa832c41098f9d9506c

atan_2 no longer exists in UFL; it is just atan2. We call at atan_2 in flow.py for pinball and cylinder. I can quickly fix and add pull request so long as it doesn't effect anything you're doing @ludgerpaehler ?

**Comment by ludgerpaehler** [comment]
Go for it!
