### ISSUE TITLE
Time-stepper broken for IPCS with latest version of Firedrake

### ISSUE THREAD

**Issue by SamAhnert** [dynamicslab/hydrogym#104]
IPCS in solver.py fails to generate transient solutions when using the solver.step(_args_) to apply control (the main way we apply control to the environments). This means that the only working solver at the moment with the newest version of firedrake is NewtonSolve. It appears that within the solver.step, it is no longer possible to apply dirichlet boundary conditions by doing `Bu * fd.Constant(ctrl)` as done on line 188 in solver.py on the main branch. I assume firedrake issued some breaking changes recently since it doesn't look like we've changed this functionality in 7 months.

Issue can be recreated by running the test_cyl.py test suite on my branch (sa/bug-fix-Oct23) on the most current version of firedrake. I took a stab at fixing it today, but firedrake is not my forte. Will try to come back to it as I have time.

**Comment by ludgerpaehler** [comment]
Do you want to join the call with Nacime on Friday? Might be quickest option to triage all these issues?

**Comment by ludgerpaehler** [comment]
Will fix as soon as I get into the office in the morning, but we need to find a better isolation for Firedrake to prevent these issues blowing up into our faces every other week..

**Comment by SamAhnert** [comment]
Happy to join if it'll help. Maybe there's a quick solve you guys will know of.

**Comment by SamAhnert** [comment]
I think if we define the version of FD that hydrogym is compatible with and have a corresponding FD docker container to pip install hydrogym into, we won't have to worry about keeping up with the constant evolution of FD. I know we've been trying to avoid making docker containers the way to use hydrogym though.

Overall, two or three breaking changes over the course of nearly a year probably isn't too bad though. But adding other solvers is definitely good long term insurance.

**Comment by ludgerpaehler** [comment]
The (big & breaking) update I am currently working to finish does in essence that (-ish):

- Auto-launches Ray cluster for HydroGym to live on (on top of Slurm or whatever is available)
- Uses Ray Environments & Docker to isolate the environments themselves in order for us to be able to push a working pip-package which _just works_ while at the same time opening us up to be able to integrate a wider variety of solvers.

**Comment by ludgerpaehler** [comment]
Hope I am not being too dictatorial in pushing for this big change 😅
