### ISSUE TITLE
Discrete-time LTI

### ISSUE THREAD

**Issue by jcallaham** [dynamicslab/hydrogym#16]
Realized that using the DirichletBC as a control matrix doesn't really make sense in continuous time models, since it's applied at discrete time steps.  What you currently get from FlowConfig.linearize_control() is actually something like `dt*B`, except that there's no `dt` specified... so in order to use it in a continuous-time model you have to multiply by the timestep you *will* be using... which is kind of a mess.

But I think you could do an equivalent (maybe cleaner) thing by moving the control to the timestepper.  Since applying a zero DirichletBC in initial assembly will set corresponding rows of the dynamics matrix to identity, and rows of the RHS to zero, you could just precompute the discrete-time control vector (which is what we already have) and apply it as `x_{k+1} = A*x_k + B*u_k`, where `A` is quasilinear.  I think this will work for the forseeable future, since all planned controls are on Dirichlet BCs.  This could actually be a cleaner implementation of the timestepping, too.  Then you should just be able to get `A` as a LinearOperator.

- [x] Change control from time-varying DirichletBC to forcing vector in timestepping
- [x] Check this is differentiable
- [x] Wrap timestepping as LinearOperator
- [x] Check eigenvectors with `eigs` in scipy
- [ ] Same for adjoint operator

**Comment by ludgerpaehler** [comment]
Not current any more.
