### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by ludgerpaehler** [dynamicslab/hydrogym#39]
We need to begin enforcing a coding style. The most commonly used options for this would be [flake8](https://flake8.pycqa.org/en/latest/) or [black](https://black.readthedocs.io/en/stable/).

Thought? Feelings? @jcallaham @SamAhnert

**Comment by jcallaham** [comment]
Agreed.  I've used black but not flake8, so I don't feel strongly.  You?

**Comment by SamAhnert** [comment]
I also have no preference (haven't used either before). Will leave the choice to you both!

**Comment by ludgerpaehler** [comment]
Shall we go with black then? It does seem to be a pretty standard choice for most of the modern Python projects.

In the same step we could also directly add a `CONTRIBUTING.md` statement. As the project is already public it would be good to show people a direct way to contribute to the effort if they accidentally stumble over it and seek to contribute a few cycles.

**Comment by ludgerpaehler** [comment]
Please see the linked pull-request. Added everything, and the style files also get recognized automatically by your typical VS-Code when opening the project.

**Comment by jcallaham** [comment]
Also see #43 for actually making the new changes
