### ISSUE TITLE
Writing up Documentation as we go along

### ISSUE THREAD

**Issue by ludgerpaehler** [dynamicslab/hydrogym#47]
While not an absolute necessity for the paper submission, it would probably be helpful to start writing up docs as we go along (and still have a lot of the stuff fresh in our memory).

What am I proposing?
1. Deploy an initial readthedocs bare-bones documentation
2. Document new stuff as we along without looking at the form, or the finer formulation of the notes

I.e. we would basically have a bare-bones documentation with notes inside of it at the end, over which we can comb over after the paper submission to then have the actual documentation, and for which we can also adjust the style files etc.

**Comment by ludgerpaehler** [comment]
Opened a first WIP pull-request to have an initial version of the documentation online. Will complete to mergable state later today.

**Comment by ludgerpaehler** [comment]
@jcallaham @SamAhnert what do you think?

**Comment by jcallaham** [comment]
Sounds great to me and #48 looks good.  When we get to that stage (or maybe sooner) I can also make a more thorough pass at typing and docstrings, which will hopefully make the code more understandable with or without detailed docs.

**Comment by SamAhnert** [comment]
Sound like a great idea to me too! Are there any dependencies we'll need installed to add to the documentation or to make sure our formatting is consistent between the three of us?

**Comment by ludgerpaehler** [comment]
No dependencies, readthedocs builds the entire thing automatically periodically.

I think as long as Sphinx compiles, the docs will look sort of the same to the user. So no style-constraints :)
