### ISSUE TITLE
Hardcoded analytic torque value in `test_cyl.py`

### ISSUE THREAD

**Issue by jcallaham** [dynamicslab/hydrogym#59]
@SamAhnert one of the new tests for the torque-based actuation has a value in it that looks like something calculated based on a specific value of `TAU = 0.0556`.  Here's the test:

```
def test_fixed_torque():
    print("")
    print("Fixed Torque Convergence")
    time_start = time.time()
    flow = hgym.Cylinder(mesh="coarse", control_method="indirect")
    dt = 1e-3
    solver = hgym.IPCS(flow, dt=dt)
    flow.actuators[0].implicit = True

    # Apply steady torque of 35.971223 Nm, should converge to ~2 rad/sec with k_damp = 1/TAU
    tf = 1e-2  # sec
    torque = 35.971223  # Nm <--- HERE'S THE VALUE

    # Run sim
    num_steps = int(tf / dt)
    for iter in range(num_steps):
        flow = solver.step(iter, control=torque)

        print(flow.control_state)

    assert np.isclose(flow.control_state, 2.0, atol=1e-3)

    print("finished @" + str(time.time() - time_start))
```

Could you make this calculation transparent so that we can change `Cylinder.TAU` and still have it calculate the right value?  This snippet is from the release branch, but you could just commit the change to master and I'll merge it from there.

**Comment by SamAhnert** [comment]
Should be fixed in https://github.com/dynamicslab/hydrogym/commit/585edba41081c36a46507c2946e83d3d4d7d5929.
