### ISSUE TITLE
Little experience feedback after installation

### ISSUE THREAD

**Issue by ReHoss** [dynamicslab/hydrogym#64]
Hi,

First thank you for this amazing work.

I tried to install _hydrogym_ on my _Dell Ubuntu 20.04 (Intel i9)_ laptop. And I have encountered several issues:

- First I have not understood the following implementation details on the _readthedocs.io_ page: 

> In the technical approach we take to our distributed backend, we have the default assumption that the virtual environment has no access to a native [Firedrake](https://www.firedrakeproject.org/) installation, the default simulation engine powering the reinforcement learning (RL) environments, and instead the distributed backend spawns environment instances with every RL-instance.

It's not very clear how to run this instruction: `config.update("hydrogym_local_development", True)`. Where does the `config` object comes from ?

In `git clone --recursively https://github.com/dynamicslab/hydrogym.git` the flag `--recursively` did not work and I had to replace it by `--recursive`.

- Second, about Firedrake there are some installations difficulties.

Just importing `hydrogym` and run the quickstart code did not work. I had to install manually _Firedrake_ and install _hydrogym_ inside the _Firedrake_'s venv.

I first installed _Firedrake_ with the third party revision `firedrake @ 2209aae` provided by the repository. The installation failed the _Firedrake_ test suite, see https://www.firedrakeproject.org/download.html.
Consequently I installed the last release from the official _Firedrake_ repository, the test suite went fine. However, It failed again but now because of a minor `ufl` checkpoint loading bug see https://github.com/firedrakeproject/firedrake/issues/2645, and by installing a stable previous version of `ufl` inside the `venv` I was able to import hydrogym and run the overview notebook (with some code update with respect to newer versions).

I could provide `hydrogym` updated introductory `.py` scripts if necessary:).

Thanks for your consideration,

Kind regards,

**Comment by jcallaham** [comment]
Thanks for the feedback @ReHoss!  Most of the confusing stuff in the installation docs is related to running distributed instances for large-scale RL training, which we're still actively working on and is not ready for use.  So please disregard all of that.

Running "locally" should be okay (though again, consider all of this pre-release and potentially broken or incorrect at any point).  For that you do need to install Firedrake separately, as you said.  I just updated the installation docs to hopefully make that a little more clear.  We will need to settle on a version of Firedrake that we officially support, but for now I would just go with whatever seems stable.

**Comment by ReHoss** [comment]
With respect to https://github.com/firedrakeproject/firedrake/issues/2645, In fact it is not necessary to downgrade UFL.

According to the issue I mention, if I understand correctly, old .h5 data is not loadable anymore without a patch, so that's why I guess I was not able to load the data from the notebook while using a recent UFL version.

Trying to load _examples/demo/checkpoint-coarse.h5_, it worked fine with the recent UFL version provided by the installation.
