### ISSUE TITLE
Fluidic Pinball dynamic

### ISSUE THREAD

**Issue by ReHoss** [dynamicslab/hydrogym#94]
Hello:)

As not so much examples are given for the _Fluidic Pinball_, I would like to have your feedback on those elements:

- First, as @jcallaham suggested for the _Cavity Flow_  #51  and since the _Fluidic Pinball_ at $Re=130$ is chaotic I chose to derive the steady-state solution and add Gaussian noise on it $\mathcal{N}(0,  10^{-2})$ (otherwise if initialised with a null vector field the simulation could blow up as Cavity but I am not sure it is that critical in this case).

- Second, I chose a $\delta_t^{IPCS} = 10^{-3}$, I am not sure it is the right one and references often omit to mention the used values. Consequently, the flow is qualitatively constant after $t=10s$ and the _KE_ value  somehow converges. What is the best strategy to quickly obtain the chaotic fluctuating flow ? Larger noise, most instable eigenvalue (but eigenvalue part is not trivial...) ?

**Vorticity field**

![image](https://github.com/dynamicslab/hydrogym/assets/41160498/5c5b9795-62a4-48a3-95ca-d89ba18e4f5c)

**Velocity field**

![image](https://github.com/dynamicslab/hydrogym/assets/41160498/bdd2ca4f-9e5c-4c2c-b350-e79331fef529)

I started to investigate this flow because I observed exploding dynamic when starting to apply control forcing directly (sampling random actions to initialise a replay-buffer) from the transient flow initialised with a null vector field (I guess it is null by default with UFL?) through the `step` interface at $Re=130$ with a coarse grid.

PS: sorry this might be moved in discussions ?

**Comment by ReHoss** [comment]
Alright, when running the simulation again with an higher noise $\mathcal{N}(0, 10^-1)$ and when I **rescale the colorbar** to [-5, 5], for the vorticity field I get the following output at $t\simeq 32$:


**Vorticity field**
![image](https://github.com/dynamicslab/hydrogym/assets/41160498/1f5c6803-0d90-4293-a8f7-98ab5da4552a)


which looks good I guess.


However I don't get why there is explosion of the dynamics when applying random control forcing when starting with a null vector field after 40 time steps. I could soon provided more details on the controls applied.

I am going to:

- Check if there is explosion when starting from the steady state (equilibrium) flow
- Check if there is explosion when starting from the stationary flow (when the transient phase is left and the flow is on its attractor)

**Comment by ReHoss** [comment]
Actually, this might be a bug from my side, I am about to disantangle this. Thanks for all your answers:)

**Comment by jcallaham** [comment]
Just saw this - we did also end up finding a bug in the control terms for the pinball, so #132 (still in review at the moment) might help if you're still having any trouble with this.  I'm going to close out for now, unless you have other issues after we get that merged.
